import 'dart:async';
import 'package:flutter/material.dart';

class ThemeHelper {
  static StreamController<String> controller = StreamController<String>();

  static BaseTheme? theme() => _getDefaultTheme();

  static String? _appTheme;

  static Stream<String> appthemeString = controller.stream;

  static Map<String, BaseTheme> _supportedThemes = {
    "white": BaseTheme(),
    "dark": DarkTheme(),
    "custom": CustomTheme(),
  };

  static BaseTheme? _getDefaultTheme() {
    //return default strings if locale is not set

    if (_appTheme == null) return BaseTheme();

    //throw exception to notify given local is not found or not generated by the generator

    if (!_supportedThemes.containsKey(_appTheme))
      throw Exception(
          "$_appTheme is not found.\n Make sure you have added this locale in JSON file\n Try running flutter pub run build_runner");

    //return locale from map

    return _supportedThemes[_appTheme!];
  }

  static void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
    controller.add(_newTheme);
  }
}

class DarkTheme extends BaseTheme {
  @override
  Color get colorPrimary => Colors.pink;
}

class CustomTheme extends BaseTheme {
  @override
  Color get colorPrimary => fromHex("#4EB45E");
  @override
  Color get selectedFilterColor => fromHex("#F2FCF4");

  @override
  Color get unSelectedBgColor => fromHex("#f7f7f7");
}

class BaseTheme {
  Color get colorPrimary => fromHex("#294572");
  Color get whitePrimary => fromHex("#FFFFFF");
  Color get grey => fromHex("#FFFFFF");

  TextStyle get text12SemiBoldRed {
    return TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.8,
        color: Colors.red);
  }

  TextStyle get text14SemiBolddBlack {
    return TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.8,
    );
  }

  TextStyle get text14SemiGrey {
    return TextStyle(
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.8,
        color: Colors.grey);
  }

  TextStyle get text24BoldBlack {
    return TextStyle(
      fontSize: 24,
      fontWeight: FontWeight.bold,
      letterSpacing: 0.8,
    );
  }
}

BaseTheme? get appTheme => ThemeHelper.theme();

Color fromHex(String hexString) {
  final buffer = StringBuffer();
  if (hexString.length == 6 || hexString.length == 7) buffer.write('ff');
  buffer.write(hexString.replaceFirst('#', ''));
  return Color(int.parse(buffer.toString(), radix: 16));
}
